version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: gamehub-backend-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db_gamehub_volume:/var/lib/postgresql/data

  app:
    container_name: gamehub-backend-app
    build:
      context: .
    ports:
      - '3003:3003'
    command:
      - sh
      - -c
      - |
        npx prisma generate
        npx prisma db push
        npm start
    depends_on:
      - db

volumes:
  db_gamehub_volume:
