version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: gamehub-backend-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3003:3003'
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ignore:/app/node_modules/

volumes:
  postgres_data:
  ignore:
