version: '3'
services:
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"

  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
