version: '3.1'

services:
  app:
    container_name: gamehub-backend-app
    build:
      context: .
    ports:
      - '3003:3003'
    command:
      - sh
      - -c
      - |
        npx prisma generate
        npx prisma db push
        npm start
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    container_name: gamehub-backend-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-app-data-pc-host:/var/lib/postgresql/data

volumes:
  docker-app-data-pc-host:
